keyUp = keyboard_check(ord("W"))
keyDown = keyboard_check(ord("S"))
keyLeft = keyboard_check(ord("A"))
keyRight = keyboard_check(ord("D"))
if keyUp debug.log("I am pressing W")
if keyDown debug.log("I am pressing S")
if keyLeft debug.log("I am pressing A")
if keyRight debug.log("I am pressing D")